### ISSUE TITLE
Please help me to use this repo

### ISSUE THREAD

**Issue by freakeinstein** [actionml/chef-pio#15]
Hi, I would like install prediction IO for the first time to test run it. I see from the readme that, AIO is good for testing. But how to install predictionIO AIO in my system with this repo? Can someone help?

**Comment by dennybaa** [comment]
Hi,
follow standard installation approach.
1. install chef
2. install berkshelf
3. clone this repo
4. vendor cookbooks with berkshelf
5. chef-client -z -r pio::aio
