### ISSUE TITLE
cant run on AWS OpsWorks

### ISSUE THREAD

**Issue by augustocsmartins** [actionml/chef-pio#20]
Hi,
I'm trying to deploy to AWS Opsworks, but I'm getting this error. I don't know if I'm missing some custon configuration. Please, help.

-----
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
 
 
================================================================================
Recipe Compile Error in /var/chef/runs/60755da9-807a-4051-8e50-e675233d49b5/local-mode-cache/cache/cookbooks/pio/recipes/aio.rb
================================================================================
 
NoMethodError
-------------
undefined method `compact' for #<Hash:0x00000004d69b48>
 
Cookbook Trace:
---------------
/var/chef/runs/60755da9-807a-4051-8e50-e675233d49b5/local-mode-cache/cache/cookbooks/pio/libraries/helpers.rb:85:in `apache_vars'
/var/chef/runs/60755da9-807a-4051-8e50-e675233d49b5/local-mode-cache/cache/cookbooks/pio/recipes/default.rb:123:in `block in from_file'
/var/chef/runs/60755da9-807a-4051-8e50-e675233d49b5/local-mode-cache/cache/cookbooks/pio/recipes/default.rb:116:in `from_file'
/var/chef/runs/60755da9-807a-4051-8e50-e675233d49b5/local-mode-cache/cache/cookbooks/pio/recipes/aio.rb:18:in `from_file'
 
Relevant File Content:
----------------------
/var/chef/runs/60755da9-807a-4051-8e50-e675233d49b5/local-mode-cache/cache/cookbooks/pio/libraries/helpers.rb:
 
78:          pio_home: pio_home
79:        }
80:      end
81:  
82:      # Apache vars: contains substituted appdir if app has been passed.
83:      def apache_vars(**args)
84:        args[:appdir] = ::File.join(localdir, args[:app])
85>>       default_variables.merge(args).compact
86:      end
87:  
88:      def provision_only?
89:        node['pio']['provision_only']
90:      end
91:  
92:      def service_actions
93:        provision_only? ? [:enable] : [:enable, :start]
94:      end
 
Platform:
---------
x86_64-linux
 
[2018-06-08T20:09:19+00:00] ERROR: Running exception handlers
[2018-06-08T20:09:19+00:00] ERROR: Exception handlers complete
[2018-06-08T20:09:19+00:00] FATAL: Stacktrace dumped to /var/chef/runs/60755da9-807a-4051-8e50-e675233d49b5/local-mode-cache/cache/chef-stacktrace.out
[2018-06-08T20:09:19+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-06-08T20:09:19+00:00] ERROR: undefined method `compact' for #<Hash:0x00000004d69b48>
[2018-06-08T20:09:19+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by dennybaa** [comment]
it's not supposed too, that stuff uses outdated ruby as it seems...
