### ISSUE TITLE
Cookbook tries to install HBase 1.2.5, which no longer is available in apache mirrors

### ISSUE THREAD

**Issue by jsyrjala** [actionml/chef-pio#4]
Cookbook tries to install HBase from here http://apache.mirrors.tds.net/hbase/1.2.5/hbase-1.2.5-bin.tar.gz. It seems that apache mirrors no longer have that version, instead they have 1.2.6.

**Comment by dennybaa** [comment]
@jsyrjala Hi, this is the way how it works. Apache always cleans up dists as they update release. You can always set corresponding attributes to use the version which is available.
However we don't track their updates... Please send a PR, or I'll update myself as I get there.
